/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.WeatherApiExample;

import com.example.frames.WeatherApiExample.WeatherFrame;

/**
 *
 * @author Nathan Snow
 */
public class App {

    public static void main(String[] args) {
        /* Create and display the GUI form */
        java.awt.EventQueue.invokeLater(() -> {
            WeatherFrame weatherFrame = new WeatherFrame();
            weatherFrame.setVisible(true);
        });
    }
}
