/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.example.frames.WeatherApiExample;

import com.example.WeatherApiExample.ApiCall;
import com.example.WeatherApiExample.CityNotFoundException;
import java.awt.event.KeyEvent;
import java.util.Map;
import java.util.logging.Level;

/**
 *
 * @author Nathan Snow
 */
public class WeatherFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(WeatherFrame.class.getName());
    private final String WEATHER_RESULT_LOADING_TEXT = "Loading weather for %s...";
    private final String WEATHER_RESULT_TEXT = "The temperature in %s is %.2f°C";
    
    /**
     * Creates new form WeatherFrame
     */
    public WeatherFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        weatherResultLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cityInput = new javax.swing.JTextField();
        showTempBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        weatherResultLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        weatherResultLabel.setText("Enter a city to view the current temperature");

        jLabel1.setText("City:");

        cityInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cityInputKeyReleased(evt);
            }
        });

        showTempBtn.setText("Show Temperature");
        showTempBtn.addActionListener(this::showTempBtnActionPerformed);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(cityInput, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(showTempBtn)))
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(weatherResultLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cityInput, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showTempBtn))
                .addGap(50, 50, 50)
                .addComponent(weatherResultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(124, Short.MAX_VALUE))
        );

        weatherResultLabel.getAccessibleContext().setAccessibleName("weatherResultLabel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(425, 337));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Fetch the temperature by the user clicking the show temp button
     * @param evt The {@link KeyEvent}
     */
    private void showTempBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showTempBtnActionPerformed
        showTemp();
    }//GEN-LAST:event_showTempBtnActionPerformed

    /**
     * Fetch the temperature by the user pressing enter
     * @param evt The {@link KeyEvent}
     */
    private void cityInputKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cityInputKeyReleased
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            this.showTemp();
        }
    }//GEN-LAST:event_cityInputKeyReleased

    /**
     * This method performs the following tasks:
     * 
     * 1. Gets the city name form the user.
     * 2. Queries the OpenWeatherMap geocode API for the city name and gets the coordinates 
     *    for that city in response (or shows an error if that city cannot be found).
     * 3. Queries the OpenWeatherMap weather API with the city coordinates.
     * 4. Displays the current temperature at the target city.
     */
    private void showTemp(){
        // Ensure the label text is normal color
        weatherResultLabel.setForeground(new java.awt.Color(60,63,65));
        
        // Get the city name from cityInput
        String targetCity = capitalizeCityName(cityInput.getText().trim());
        
        // Show loading text
        weatherResultLabel.setText(String.format(WEATHER_RESULT_LOADING_TEXT, targetCity));
        
        // Perform API call in a new thread to brevent the program from 'hanging'
        new Thread(() -> {
            logger.log(Level.INFO, "Fetching weather for {0}", targetCity);
            
            //Call the weather API and get the coordinates for the given city name
            ApiCall apiCall = new ApiCall();
            try {
                Map<String, Double> coords = apiCall.getCoordinatesByLocationName(targetCity);
                
                // Call the weather API to get the weather for those coordinates
                Double temp = apiCall.getWeatherData(coords.get("lat"), coords.get("lon"));
                
                // Set the weather result label text to show the current temperature for the given city
                String labelText = String.format(WEATHER_RESULT_TEXT, targetCity, temp);
                weatherResultLabel.setText(labelText);
            } catch (CityNotFoundException e){
                logger.log(Level.WARNING, e.getMessage());
                // Change the font color and show an error message
                weatherResultLabel.setForeground(new java.awt.Color(255, 102, 102));
                weatherResultLabel.setText(e.getMessage());
            }
        }).start();
    }
    
    /**
     * Takes a city name comprising of one or more words and returns it with each word capitalized. This is simply for cosmetics.
     * @param cityName The name of the city
     * @return The name with each word being capitalized
     */ 
    private String capitalizeCityName(String cityName){
        if (cityName == null || cityName.isEmpty()) return cityName;

        String[] words = cityName.split(" ");
        for(int i = 0; i < words.length; i++){
            String word = words[i];
            if (!word.isEmpty()) {
                words[i] = word.substring(0, 1).toUpperCase() + word.substring(1).toLowerCase();
            }
        }
        return String.join(" ", words);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cityInput;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton showTempBtn;
    private javax.swing.JLabel weatherResultLabel;
    // End of variables declaration//GEN-END:variables
}
